# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: amaker
email: itamaker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  你的时间有限，不要浪费于重复别人的生活。不要让别人的观点淹没了你内心的声音。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jiazhaoyang.com" # the base hostname & protocol for your site
twitter_username: itamaker
github_username:  itamaker

# Build settings
markdown: kramdown
